version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meetly-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Укажи путь к бэкенду
      dockerfile: Dockerfile
    container_name: meetly-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/meetly
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: meetly-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meetly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: meetly-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
